---
- hosts: web
  user: ubuntu
  become_method: sudo
  become: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - dependencies
    - prepare