---
# tasks file for apache
  - name: Creating web directory
    file:
      path: ~/web
      state: directory

  - name: Copy index.j page to remote repository
    copy:
      src: files/index.js
      dest: ~/web/index.js
      owner: ubuntu
      group: ubuntu
      mode: u=rwx,g=rx,o=rx
      
  - name: Executing node
    shell: |
      pm2 start ~/web/index.js -f