---
# tasks file for apache
  - name: Update server
    apt:
      update_cache: yes
  - name: Upgrade
    apt:
      name: "*"
      update_cache: yes
  - name: Install dependencies
    apt:
      name: [npm,nodejs]
      state: latest
  - name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

       

          
